name: C/C++ CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: sudo apt-get -y install cmake

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: cmake --build build --target test
